# mlFlow Registry QA & Prod pipeline
variables:
- group: Databricks-environment

trigger:
- staging
- master
- dev

pool:
  name: Hosted Ubuntu 1604

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.7'
  inputs:
    versionSpec: 3.7

- script: |
    pip install pytest requests setuptools wheel pyspark==2.4.5
#    pip install -U databricks-cli
  displayName: 'Load Python Dependencies'

- task: riserrad.azdo-databricks.azdo-databricks-configuredatabricks.configuredatabricks@0
  inputs:
    url: '$(WORKSPACE_REGION_URL)/?o=$(WORKSPACE_ORG_ID)'
    token: '$(DATABRICKS_TOKEN)'
  displayName: 'Configure Databricks CLI for AZDO'

#- script: |
#    dbfs ls
#  displayName: 'Check config working'

- checkout: self
  persistCredentials: true
  clean: true

- script: git checkout $(Build.SourceBranchName)
  displayName: 'Get Latest from Branch $(Build.SourceBranchName)'

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: '$(Build.Repository.LocalPath)/cicd-scripts/executenotebook.py'
    arguments: '--shard $(DATABRICKS_HOST) --token $(DATABRICKS_TOKEN) --cluster $(EXISTING_CLUSTER_ID) --localpath $(Build.Repository.LocalPath)/notebooks/Users/$(Username)/train_model.py --workspacepath /Users/miguel.peralvo@databricks.com/demos/automation/run/ --outfilepath /home/vsts/work/1/s/pipeline --params model_name=$(model_name)'
  displayName: 'Train the new version of the model'


- script: |
    cat /home/vsts/.databrickscfg
    echo ""
    echo "-------------"
    dbfs ls dbfs:/Users/$(USERNAME)/Demo/Test/deploy_azure_ml_model --profile AZDO
    dbfs rm --recursive dbfs:/Users/$(USERNAME)/Demo/Test/deploy_azure_ml_model --profile AZDO
    dbfs cp --overwrite  $(Build.Repository.LocalPath)/"pipeline/ML/deploy/deploy_azure_ml_model.py" dbfs:/Users/$(USERNAME)/Demo/Test/deploy_azure_ml_model/deploy_azure_ml_model_2.py --profile AZDO
    dbfs ls dbfs:/Users/$(USERNAME)/Demo/Test/deploy_azure_ml_model --profile AZDO
    databricks workspace import $(Build.Repository.LocalPath)/"pipeline/ML/deploy/deploy_azure_ml_model.py" "dbfs:/Users/$(USERNAME)/Demo/Test/deploy_azure_ml_model"  --language PYTHON -o --profile AZDO
  displayName: 'Import ML Deploy Notebook'

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: '$(Build.Repository.LocalPath)/cicd-scripts/executenotebook.py'
    arguments: '--shard $(WORKSPACE_REGION_URL)/?o=$(WORKSPACE_ORG_ID) --token $(DATABRICKS_TOKEN) --cluster $(EXISTING_CLUSTER_ID) --localpath $(Build.Repository.LocalPath)/pipeline/ML/deploy --workspacepath /Demo/Test --outfilepath /home/vsts/work/1/s/pipeline --params model_name=$(model_name)'
  displayName: 'Deploy mlFlow Model from Registry to Azure ML for Testing'
  
- script: |
    echo $(response)
  displayName: 'API URL'
- script: |
    databricks workspace import $BUILD_SOURCESDIRECTORY/"pipeline/ML/test/test_api.py" "/Demo/Test/test_api"  --language PYTHON -o --profile AZDO
  displayName: 'Import ML Test Notebook'
- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: '$(Build.Repository.LocalPath)/cicd-scripts/executenotebook.py'
    arguments: '--shard $(WORKSPACE_REGION_URL)/?o=$(WORKSPACE_ORG_ID) --token $(DATABRICKS_TOKEN) --cluster $(EXISTING_CLUSTER_ID) --localpath $(Build.Repository.LocalPath)/pipeline/ML/test --workspacepath /Demo/Test --outfilepath /home/vsts/work/1/s/pipeline --params model_name=$(model_name),scoring_uri=$(response)'
  displayName: 'Test mlFlow Model from Registry against REST API' 

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: '$(Build.Repository.LocalPath)/cicd-scripts/mlflow.py'
    arguments: ''
  displayName: 'Promote mlFlow Registry model to Production' 

- script: |
    echo $(response)
  displayName: 'Model Production Version'

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: '$(Build.Repository.LocalPath)/cicd-scripts/executenotebook.py'
    arguments: '--shard $(WORKSPACE_REGION_URL)/?o=$(WORKSPACE_ORG_ID) --token $(DATABRICKS_TOKEN) --cluster $(EXISTING_CLUSTER_ID) --localpath $(Build.Repository.LocalPath)/pipeline/ML/deploy --workspacepath /Demo/Test --outfilepath /home/vsts/work/1/s/pipeline --params model_name=$(model_name),stage="production,phase="prod"'
  displayName: 'Deploy mlFlow Model from Registry to Azure ML into Production'